---
- name: install epel-release
  yum:
    name: epel-release
    state: present
- name: install nginx
  yum:
    name: nginx
    state: present
  notify: restart nginx
- name: copy config file
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
